# Generated by Django 5.0.3 on 2024-03-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobcategorymodel_jobtypemodel_skillmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.DateField(max_length=8)),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.CharField(blank=True, max_length=2000, null=True)),
                ('bidamount', models.IntegerField()),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postjobmodel')),
                ('costomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.costomerprofilemodel')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dealerprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bidamountmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('costomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.costomerprofilemodel')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dealerprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_signature', models.CharField(blank=True, max_length=150)),
                ('amount', models.IntegerField()),
                ('paymentReport', models.BooleanField(default=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('costomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.costomerprofilemodel')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.dealerprofilemodel')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.postjobmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(null=True, upload_to='media/screenshot')),
                ('keyups', models.IntegerField()),
                ('mouseclicks', models.IntegerField()),
                ('duration', models.DateTimeField(auto_now_add=True, null=True)),
                ('seconds', models.FloatField(null=True)),
                ('task', models.CharField(max_length=255, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bidamountmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
